DROP SEQUENCE MEMBERSEQ;
DROP TABLE MEMBER;

CREATE SEQUENCE MEMBERSEQ;
CREATE TABLE MEMBER(
	MEMBERNO NUMBER PRIMARY KEY,
	MEMBERID VARCHAR2(1000) NOT NULL,
	MEMBERPW VARCHAR2(1000) NOT NULL,
	MEMBERNAME VARCHAR2(1000) NOT NULL,
	MEMBERPHONE VARCHAR2(2000) NOT NULL,
	MEMBERADDR VARCHAR2(3000) NOT NULL
	
);

INSERT INTO MEMBER VALUES(MEMBERSEQ.NEXTVAL,'ADMIN','ADMIN123','안지민','010-0000-0000','경기도 권선구 권선동');

SELECT * FROM MEMBER;